server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: booking-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
